ALTER TABLE USER_ADDRESS
    ADD CONSTRAINT FK_USERS FOREIGN KEY (USER_ID)
        REFERENCES USERS;

ALTER TABLE USER_ADDRESS
    ADD CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID)
        REFERENCES ADDRESS;